name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: build
        run: go build cmd/main.go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59

